version: '3'

services:
  nginx:
    image: library/nginx:latest
    ports:
    - 80:80
    volumes:
    - /home/ming/blog/nginx/html:/usr/share/nginx/html
    - /home/ming/blog/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  mysql:
    image: library/mysql:5.7
    ports:
    - 3306:3306
    volumes:
    - /home/ming/blog/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    image: library/redis:latest
    ports:
    - 6379:6379
  myblog:
    build: .
    image: myblog:1.0
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - redis